### ISSUE TITLE
Clicking a user's usergroup should display the usergroup

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#16]
On the `menuitem-admin_security_user` page, User management, clicking on anything that belongs to a user takes the visitor to the user's view page. When clicking the user's usergroup, the visitor should be taken to the usergroup's view page.

**Comment by phax** [comment]
Good point - thanks.
As this is part of a basic component I cannot update for 4.1.1, it will be part of the next 5.0.0 release.

**Comment by OskarD** [comment]
Great! Thank you :)

**Comment by phax** [comment]
Fixed in HEAD revision of ph-oton
