### ISSUE TITLE
No feedback when adding service group fails

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#17]
I'm trying to add a Service group using the GUI, but the page just reloads after about half a second when I click on "Save". There is no feedback about what happened, and it does not appear in the list of service groups afterwards.

My SML connection is active (SMK)

**Comment by OskarD** [comment]
I just added another Service Group and it worked, so I retried the first one and it worked too. I don't know what changed. This is strange.

**Comment by phax** [comment]
This is indeed strange. Upon edit and create I'm using the POST-REDIRECT-GET pattern to avoid a double creation when using the back button.
Are you on the latest version of the SNAPSHOT?

**Comment by OskarD** [comment]
I am using 4.1.1-SNAPSHOT

It wasn't created at all, it didn't show up in the list. It just refreshed the page (I tried multiple times, waited for the page to reload before I tried again).

**Comment by phax** [comment]
Did you potentially restart the Tomcat while the edit/create page was open?
Maybe you fell into the CSRF check???? So if you restart Tomcat you need to login again for everything to work properly!

**Comment by OskarD** [comment]
It might be that I had restarted the client without logging out and back in. I will let you know if it happens again! Thank you

**Comment by phax** [comment]
In case it happens again, please check the Tomcat logfile whether it contains a ERROR line containing "CSRF"....
