### ISSUE TITLE
'Connected to SML' toggle button in the UI

### ISSUE THREAD

**Issue by hmspider** [phax/peppol-smp-server#19]
This button would set the `sml.active` property to true/false. There could also be a textfield next to it to write the `sml.url`.

Upon _activating_ the toggle, the smp-server would update changes to the smp indicated in the textfield. The field would be grayed-out and inactive.

Upon _deactivating_ the toggle, the text field would become active. This means that in order to change SML you'd have to disconnect first.

Thanks!

**Comment by phax** [comment]
A new page "SMP Settings" was added in the "Administration" area where you can enable/disable SML connection. It contained starting with SNAPSHOT 51.

**Comment by hmspider** [comment]
Neat!
