### ISSUE TITLE
(New feature) Include SML registration tool in managment GUI

### ISSUE THREAD

**Issue by hmspider** [phax/peppol-smp-server#22]
same as in http://peppol.helger.com/public/menuitem-tools-smp-sml

For instance, one wouldn't need to upload the keystore & password

**Comment by phax** [comment]
Thanks for the suggestion - very helpful!

**Comment by phax** [comment]
It's nearly finished, except that only the hard coded URLs are available

**Comment by phax** [comment]
The SML registration tool now uses the customizing SML URLs from #23
