### ISSUE TITLE
Private IP address sometimes showing up in SMP lookup instead of PEPPOL name

### ISSUE THREAD

**Issue by AlessandroSolano** [phax/peppol-smp-server#26]
I've been noticing this issue since I first installed peppol-smp-server on Tomcat last april. Sometimes the server just replies to SMP queries with a URI containing its private IP instead of its PEPPOL name, as you can see from this copied text from the participant lookup tool:

> ServiceGroup contents

    https://10.0.4.102/iso6523-actorid-upis::9906:07649050965/services/busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2::DespatchAdvice##urn:www.cenbii.eu:transaction:biitrns016:ver1.0:extended:urn:www.peppol.eu:bis:peppol30a:ver1.0:extended:urn:www.ubl-italia.org:spec:ddt:ver2.1::2.1
    busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2::DespatchAdvice##urn:www.cenbii.eu:transaction:biitrns016:ver1.0:extended:urn:www.peppol.eu:bis:peppol30a:ver1.0:extended:urn:www.ubl-italia.org:spec:ddt:ver2.1::2.1
    Open in browser
    https://10.0.4.102/iso6523-actorid-upis::9906:07649050965/services/busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Order-2::Order##urn:www.cenbii.eu:transaction:biitrns001:ver2.0:extended:urn:www.peppol.eu:bis:peppol3a:ver2.0:extended:urn:www.ubl-italia.org:spec:ordine:ver2.1::2.1
    busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Order-2::Order##urn:www.cenbii.eu:transaction:biitrns001:ver2.0:extended:urn:www.peppol.eu:bis:peppol3a:ver2.0:extended:urn:www.ubl-italia.org:spec:ordine:ver2.1::2.1
    Open in browser

Which makes the server unavailable for the outside public who performs SMP lookups. 
Every time I notice that, I reload the application and right after that the query result looks correct:

> ServiceGroup contents

    http://B-33caed61f912b1ee53399e01e0492fdf.iso6523-actorid-upis.edelivery.tech.ec.europa.eu/iso6523-actorid-upis::9906:07649050965/services/busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2::DespatchAdvice##urn:www.cenbii.eu:transaction:biitrns016:ver1.0:extended:urn:www.peppol.eu:bis:peppol30a:ver1.0:extended:urn:www.ubl-italia.org:spec:ddt:ver2.1::2.1
    busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:DespatchAdvice-2::DespatchAdvice##urn:www.cenbii.eu:transaction:biitrns016:ver1.0:extended:urn:www.peppol.eu:bis:peppol30a:ver1.0:extended:urn:www.ubl-italia.org:spec:ddt:ver2.1::2.1
    Open in browser
    http://B-33caed61f912b1ee53399e01e0492fdf.iso6523-actorid-upis.edelivery.tech.ec.europa.eu/iso6523-actorid-upis::9906:07649050965/services/busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Order-2::Order##urn:www.cenbii.eu:transaction:biitrns001:ver2.0:extended:urn:www.peppol.eu:bis:peppol3a:ver2.0:extended:urn:www.ubl-italia.org:spec:ordine:ver2.1::2.1
    busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Order-2::Order##urn:www.cenbii.eu:transaction:biitrns001:ver2.0:extended:urn:www.peppol.eu:bis:peppol3a:ver2.0:extended:urn:www.ubl-italia.org:spec:ordine:ver2.1::2.1
    Open in browser

What can be the cause of the issue?

Many Thanks for your great work,

Alessandro

**Comment by AlessandroSolano** [comment]
I just saw this entry in the log while tailing catalina.out BTW:

`[SMP-SERVER] [INFO ] [http-bio-443-exec-116] Static server information set: [StaticServerInfo@0x17a517cd: scheme=https; serverName=10.0.4.102; serverPort=443; contextPath=; fullServerPath=https://10.0.4.102; fullServerAndContextPath=https://10.0.4.102] -- com.helger.web.servlet.server.StaticServerInfo.init(StaticServerInfo.java:147)`

Which probably can help identify the root of the problem

**Comment by phax** [comment]
In the configuration file a property `smp.publicurl` is available.
This property has the sole purpose of identifying the "public URL" of the SMP server.

What you described is a problem that the web application cannot determine the host it is running on until the first request comes in. Depending on the URL of the first request, the internal "server name" is stored to something else. As a workaround you can set the aforementioned property in the configuration file (and restart the server).

hth, Philip

**Comment by AlessandroSolano** [comment]
That worked like a charm, thank you! 

Alessandro

**Comment by phax** [comment]
Glad it solves the problem. If you have any further problems, just file an issue :)

**Comment by phax** [comment]
And btw. see https://github.com/phax/peppol-smp-server/wiki/Configuration#smp-serverproperties for a list of all configuration properties
