### ISSUE TITLE
SML entry showing wrong SMP url

### ISSUE THREAD

**Issue by vitthalaa** [phax/peppol-smp-server#39]
We hosted SMP server on domain http://peppol.bluzor.com. But when we search participant in your tool, we get host in service group content as http://s1.16cnc.com. Actually it should be http://peppol.bluzor.com.

Any idea why this happening?

**Comment by phax** [comment]
Hi Vitthal!
This is simly, because I'm doing a reverse DNS lookup there.
I checked the information in the SML and everything seems to be fine!

Actually the DNS system returns PEPPOL-BLUZOR-SMP1.publisher.acc.edelivery.tech.ec.europa.eu. which is in turn by CNAME forwared to peppol.bluzor.com. So all fine!

// Philip

**Comment by vitthalaa** [comment]
Can you pleas check this
http://peppol.helger.com/public/menuitem-tools-participant?idschemepredef=9915&idscheme=9915&idvalue=test1&sml=digittest&action=perform

**Comment by phax** [comment]
That's fine.
The Base16 encoded md5 value of "9915:test1" is 250f0ddd60975f4d4dd137bfac81f888
So "http://B-"+base16(9915:test1)+"." + "iso6523-actorid-upis" +".acc.edelivery.tech.ec.europa.eu" (= http://B-250f0ddd60975f4d4dd137bfac81f888.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/) points to CNAME PEPPOL-BLUZOR-SMP1.publisher.acc.edelivery.tech.ec.europa.eu which is a CNAME to peppol.bluzor.com
-> all good :)

What is shown on the page is result of the following java operations:
```java
          final URL aSMPHost = new URL ("http://B-250f0ddd60975f4d4dd137bfac81f888.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/");
          final InetAddress aInetAddress = InetAddress.getByName (aSMPHost.getHost ());
          final InetAddress aNice = InetAddress.getByAddress (aInetAddress.getAddress ());
          String sNice = aNice.getCanonicalHostName ();
```
hth

**Comment by vitthalaa** [comment]
Hi Philip, thanks for you time.
Actually I talking about ServiceGroup contents part.
It has following content with wrong host name http://s1.16cnc.com.
Ideally it should be http://peppol.bluzor.com.

ServiceGroup contents
http://s1.16cnc.com/iso6523-actorid-upis::9915:test1/services/busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:www.cenbii.eu:transaction:biicoretrdm010:ver1.0:#urn:www.peppol.eu:bis:peppol4a:ver1.0::2.0

**Comment by phax** [comment]
Ah I see :)
You should set the `smp.publicurl` property in file `smp-server.properties` as described in https://github.com/phax/peppol-smp-server/wiki/Configuration

**Comment by vitthalaa** [comment]
Its working.. :+1:  Thanks Philip :)

**Comment by phax** [comment]
If you want, you can update to 5.0.0 final version :)
