### ISSUE TITLE
AP Endpoint Separation in UI

### ISSUE THREAD

**Issue by jerouris** [phax/peppol-smp-server#4]
It would be good for each user to have an endpoint created as an entity 
that he can later select for adding in an smp record, and by endpoint I 
mean the AP related info:

Endpoint URL, Certificate and Protocol.

This way adding a new document id will be easier, by just selecting the 
endpoint info from a dropdown, and when/if the endpoint data changes 
(for example certificate, url etc), than you will only need to change 
this data at the endpoint entity and not find/replace all the records 
that contain this AP

**Comment by phax** [comment]
The first thing in this direction is the following:
  * A consistency page was introduced that at least lets you easily identify what certificates are expired or are about to expire.
