### ISSUE TITLE
AP certificate renew process

### ISSUE THREAD

**Issue by elfogre** [phax/peppol-smp-server#42]
Hello Philip,

I've got a question about the process for renew a Peppol AP certificate. I know it's not related to this project, but I think you could help me.
We have asked for renew our AP certificate to Thomas Gundel and we have received a new one, but with different AP name in certificate CN. 

Is the expected behaviour in Peppol to create a new AP when you renew AP certificate? It also involves to change in our SMP all service groups to use the new AP. It won't be easy to just get a new certificate with the same AP id in the common name?

I know this question is not related to your smp server, so if you consider it spam, please close it.

Thank you very much!

**Comment by phax** [comment]
Hi Jose!
This is common practice in PEPPOL, and you need to ask Thomas for details on "why" it is done this way.
I just know that this is like this since the beginning and this is exactly why I added the `Bulk change certificate` page in the SMP :)
hth, Philip

**Comment by elfogre** [comment]
CA restrictions OK. 
I had to implement also a "bulk change" and everything worked correctly, but I find it easier if they try to solve that CA restriction with renewal of equal CN certificates. Hopefully we have our SMP server and could manage it easily, but if some AP use an external SMP without "bulk change", they could have to change manually all its smp entries.

Thank you very much! See you on AS4 workgroup ;)

**Comment by phax** [comment]
See you in AS4 working group - you may want to have a look at https://github.com/phax/ph-as4/ (still work in progress)
