### ISSUE TITLE
Phoss Client: API CRUD on Business Card

### ISSUE THREAD

**Issue by sinattieng** [phax/peppol-smp-server#43]
Good morning to every one,

We need, in order to implement services related to the new entity Business Card (BC(, having APIs to insert/update/delete that one and. 
Most important aspect, to **map**  every single field of BC with related metadata(s), e.g. in Italy we have a national code known as IPA, so it means that this code should be mapped with the related on BC, the question is : there is already the related API/modeler as UI for doing this? 

Thank youn in advance for your help.

Stefano Sinatti (Intercenter - Italy)

**Comment by phax** [comment]
Hi Stefano!
Thanks for your request.
Currently there is **not yet** a writable API for creating BusinessCards per REST service but I think it is a very good idea.
I will prepare a draft API document and circulate it in the PEPPOL Directory work group - if there are no objections, I will implement it here - ok?
// Philip

**Comment by sinattieng** [comment]
Hi Philip,

Good to know but what about mapping between single field on business card and mine? I mean, for my  subjects (e.g. italian Economic Operator), when a business card has been created i need to map fields so in order to insert the "wrapper" which represents the business card, i need to be able to do single set<Field> with a specific mapping,  or maybe my idea is wrong.

Take me updated.

Thanks,
 Stefano

**Comment by phax** [comment]
The XML Schema for the Business Card can be found at https://github.com/phax/peppol-directory/blob/master/peppol-directory-businesscard/src/main/resources/schemas/peppol-directory-business-card-20161123.xsd

This is how an example Business Card may look like:
```xml
<BusinessCard xmlns="http://www.peppol.eu/schema/pd/businesscard/20161123/">
  <ParticipantIdentifier scheme="iso6523-actorid-upis">9915:b</ParticipantIdentifier>
  <BusinessEntity registrationDate="2010-07-06">
    <Name>Austrian Federal Government</Name>
    <CountryCode>AT</CountryCode>
    <GeographicalInformation>Spread all over Austria</GeographicalInformation>
    <Identifier scheme="ZIPCode">1010</Identifier>
  </BusinessEntity>
  <BusinessEntity>
    <Name>Austrian Federal Government2</Name>
    <CountryCode>AT</CountryCode>
    <GeographicalInformation>Spread all over Austria2</GeographicalInformation>
    <Identifier scheme="ZIPCode">1020</Identifier>
  </BusinessEntity>
</BusinessCard>
```

I think it may be best, if this can be provided via an HTTP `POST`.
Does that sound reasonable to you?

**Comment by sinattieng** [comment]
It sounds good.
Thank you very much for your support, I will wait about API news, ok?
Have a great day.

Stefano

**Comment by sinattieng** [comment]
Good morning Philip,

Quoting you : "Currently there is not yet a writable API for creating BusinessCards per REST service but I think it is a very good idea."; any news about this topic? or something else about integration between SMP and PD? 

Thank you very much.
Have a nice day.

Stefano

**Comment by phax** [comment]
Work in progress. The "delete" API is already present (straight forward) and the "create" API should be available at the latest tomorrow.

**Comment by phax** [comment]
Finally it is implemented, tested and documented at https://github.com/phax/peppol-smp-server/wiki/REST-API#modifying-rest-api
n-joy

**Comment by sinattieng** [comment]
Thank you very much  Philip !
