### ISSUE TITLE
Import tool not registering in SML

### ISSUE THREAD

**Issue by ubrix** [phax/peppol-smp-server#44]
Hi,
When using the import tool for service groups the participants does not get registered in SML. Tested on SMK (acc.edelivery.tech.ec.europa.eu)

Version peppol-smp-server 5.0.2

Steps to reproduce:
Register a particpant in SMK 
Export service groups
Delete participant from service groups
Import service groups
No hit using tool: https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant

Extra steps:
Adding another participant manually
New participant searchable with tool: https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant

**Comment by phax** [comment]
Did you use the test certificate for accessing the SMK? Or did you try with a production certificate (which is meant to fail)?
Are you using a proxy server?
Can you give me an example identifier so I can check the SMK?
Find my email address in the pom.xml file

**Comment by phax** [comment]
Thanks for the email - I will keep the crowd posted with the reasons and the resolution :)

**Comment by phax** [comment]
The problem is the DNS client cache that is used by PEPPOL Practical (and the Difi tool as well).
Will try to figure out a way around this.
