### ISSUE TITLE
Add support for RDBMS for PEPPOL Directory

### ISSUE THREAD

**Issue by phax** [phax/peppol-smp-server#47]
Copy of phax/peppol-commons#18 from @dhixon
> Currently the website info says that PEPPOL directory only works with XML backend. Add support for RDBMS backend for PEPPOL directory. Preferred RDBMS backend is DB2.

**Comment by phax** [comment]
An example of the DB layout used for MySQL can be found at https://github.com/phax/peppol-smp-server/wiki/Upgrade-Guide-V5:
```sql
DROP TABLE IF EXISTS `smp_bce`;
CREATE TABLE `smp_bce` (
 `id` varchar(45) NOT NULL COMMENT 'Internal ID',
 `pid` varchar(255) NOT NULL COMMENT 'Participant/Business ID',
 `name` text NOT NULL COMMENT 'Entity name',
 `country` varchar(3) NOT NULL COMMENT 'Country code',
 `geoinfo` text COMMENT 'Geographical information',
 `identifiers` text COMMENT 'Additional identifiers',
 `websites` text COMMENT 'Website URIs',
 `contacts` text COMMENT 'Contact information',
 `addon` longtext COMMENT 'Additional information',
 `regdate` date DEFAULT NULL COMMENT 'Registration date',
 PRIMARY KEY (`id`),
 KEY `FK_pid` (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='SMP Business Card Entitiy';
```

==> If you have some DB2 DDL I'd be happy to add it to the Wiki

**Comment by phax** [comment]
I additionally linked it from https://github.com/phax/peppol-smp-server/wiki/PEPPOL-Directory-Integration

**Comment by dhixon** [comment]
I will provide the DB2 DDL after we have it working.  :-)

**Comment by jannewaren** [comment]
Hello @phax ! I'm a bit confused by this smp_bce table added in v5. Does this mean PEPPOL Directory integration works on the sql backend nowadays too? Because in smp-server.properties it says

> # Works currently only with XML backend
> smp.peppol.directory.integration.enabled=true

Is this old news? We would like to use the sql backend but wouldn't want to miss out on the possibility to take PEPPOL directory integration into use. If it does not work with sql backend yet, any ideas about the future? Will it at some point? :)

**Comment by phax** [comment]
This comment is out of date. Mea culpa. Will be deleted ASAP in HEAD....

**Comment by jannewaren** [comment]
Great! Thanks a lot!

**Comment by phax** [comment]
So to clarify it once and forever: PEPPOL Directory is supported by both backend - XML and SQL since version 5.0.0.
