### ISSUE TITLE
Error inviking ph AJAX function! No such data tables ID: start

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#5]
I have deployed the application on a Tomcat server under domain.name/smp-pilot with a proxy using a subdomain at webroot. Here is the configuration our network-magician has put together to make the proxy work:

```
<VirtualHost *:80>
...
    ProxyPass "/public"         "http://domain.name/smp-pilot/public"
    ProxyPass "/stream"         "http://domain.name/smp-pilot/stream"
    ProxyPass "/css"    "http://domain.name/smp-pilot/css"
    ProxyPass "/js"     "http://domain.name/smp-pilot/js"
    ProxyPass "/publicajax"     "http://domain.name/smp-pilot/publicajax"
    ProxyPassMatch "^(/.*)$"    "http://domain.name/smp-pilot$1"
    ProxyPassReverse "/public"  "http://domain.name/public"
    ProxyPassReverse "/stream"  "http://domain.name/stream"
    ProxyPassReverse "/css"     "http://domain.name/css"
    ProxyPassReverse "/js"      "http://domain.name/js"
    ProxyPassReverse "/publicajax"      "http://domain.name/publicajax"
    ProxyPassReverse "/"        "http://domain.name/smp-pilot/"

    ProxyPassReverseCookieDomain  "domain.name"  "smp-pilot.other-domain.name"
    ProxyPassReverseCookiePath  "/"  "/smp-pilot/"

...
</VirtualHost>

```

When I access the webpage, I get a pop-box that reads *Error inviking ph AJAX function! No such data tables ID: start*. This does not occur when I deploy the application on at webroot on my local machine.

I am using the XML backend with *smp.forceroot = true* on 4.0.3 (2015-11-09)

**Comment by phax** [comment]
Here is what our magicians put together:
```
...
   ServerName  test-infra.peppol.at:80

   Header edit "Set-Cookie: JSESSIONID=" Secure " "

   ProxyPass         /  ajp://127.0.0.1:8009/smp/
   ProxyPassReverse  /  ajp://127.0.0.1:8009/smp/
   ProxyPassReverseCookiePath /smp/ /
...
```
Note the different order in `ProxyPassReverseCookiePath`

**Comment by phax** [comment]
Btw. the problem is (most likely) that the session cookie is not available!

**Comment by OskarD** [comment]
Thank you @phax, that solved the problem!

**Comment by phax** [comment]
Excellent!
Even though I would suggest you try to simplify your configuration so that it does not depend on the application layout!

**Comment by OskarD** [comment]
I would like to, but I don't know how. Do you know where I might find a tutorial or explanation on the subject?

**Comment by phax** [comment]
I would start here: http://httpd.apache.org/docs/2.2/mod/mod_proxy.html (depends on your httpd version etc.). Unfortunately I'm also not an httpd expert :(

**Comment by OskarD** [comment]
Thanks, I'll try to give it a read!

**Comment by phax** [comment]
The only additional, proxy related setting we have in our config is:
```
   ProxyPassReverse  /  http://test-infra.peppol.at/smp/
```
but I don't know whether it really has an impact or not.

**Comment by phax** [comment]
Finally I completely setup an SMP on my machine. It uses the following setup:
  * SMP running on smp.helger.com
  * Tomcat with it's on  `<Host name="smp.helger.com">` where the SMP webapp runs as `ROOT`
  * Here's the httpd `VirtualHost` config used:

```
<VirtualHost *:80>
ServerName smp.helger.com
DocumentRoot /var/www/html
CustomLog /var/log/httpd/smp-access.log combine
ErrorLog /var/log/httpd/smp-error.log
ProxyPass / ajp://localhost:8112/

# Rewrite server name since AJP Proxy does not change the hostname
# Only if host name is different (something like http://b-2bf0137acdd8dba2dc0dd371c3f4bb5b.iso6523-actorid-upis.edelivery.tech.ec.europa.eu)
# The [P] uses proxy redirect instead of HTTP 302
RewriteEngine On
RewriteCond %{HTTP_HOST} !=smp.helger.com
RewriteRule (.*) http://smp.helger.com%{REQUEST_URI} [P]
</VirtualHost>
```

hth
