### ISSUE TITLE
/secure/menuitem-service_groups page has form with bad link for proxied servers

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#6]
When I visit http://domain.name/secure/menuitem-service_groups the form's action value doesn't account for the proxy address, but seems to fetch its own one, unlike all the other links in the application

**Comment by OskarD** [comment]
This applies to a whole lot of other places too, like links in SMP queries

**Comment by phax** [comment]
I'm aware of the problem. This should be fixed in the SNAPSHOT version but this one currently also depends on the https://github.com/phax/ph-oton SNAPSHOT version (but you should be able to simply check it out and build it with `mvn clean install`). The problem is the links escaping that especially pops up when dealing with all the ":" values.

**Comment by OskarD** [comment]
```html
<form class="" role="form" action="http://non-proxy-domain/secure/menuitem-service_groups" method="POST">
              <input name="login-action" type="hidden" value="validate-login-credentials">
              <div class="form-group">
                <label class="form-label form-label-optional" for="id82344">Email address:</label>
                <input id="id82344" class="form-control" name="userid" autofocus="autofocus" type="text" placeholder="Email address">
              </div>
              <div class="form-group">
                <label class="form-label form-label-optional" for="id82345">Password:</label>
                <input id="id82345" class="form-control" name="password" type="password" placeholder="Password">
              </div>
              <button class="btn btn-primary" type="submit">Login</button>
            </form>
```

**Comment by OskarD** [comment]
And when clicking on "Perform complete SMP query on ..." in Service Groups, I get directed to: http://non-proxied-domain/complete/*participant ID*

If I manually change the address to the proxied one, the ServiceMetadataReference tag shows the non-proxied address

**Comment by phax** [comment]
Can you check the ServerName in the httpd config file (as stated in issue #5)

**Comment by OskarD** [comment]
It's the same, but without :80 at the end

**Comment by phax** [comment]
In the Tomcat serverl.xml check if something like the following is present:
```xml
<Connector port="8009" proxyName="non-proxie.domain.com"...
```
The proxyName attribute is important!

**Comment by OskarD** [comment]
I can't add this because it may affect one of the many other web applications deployed on the same server. Is this required?

**Comment by phax** [comment]
As stated previously I'm not an expert on infrastructure topics.
I will do some googleing

**Comment by phax** [comment]
https://tomcat.apache.org/tomcat-7.0-doc/proxy-howto.html may be a starting point

**Comment by phax** [comment]
So, did you manage to find a matching configuration for you?

**Comment by OskarD** [comment]
We resorted to adding the proxyName attribute to the Connector for now, it works and it seems like it hasn't affected any other application. We will have to come up with some better way of solving this in the future, though. Thanks for your help!

**Comment by phax** [comment]
That's good news. Thanks for the update. What can I to make things more smooth? What about adding a configuration property "full-server-name" where you can define the base property yourself?

**Comment by OskarD** [comment]
That would be highly preferable! Easily configuring the application in all its aspects from one (or two) configuration files would make it much easier to use :) Ideally, it should be "plug-and-play" (Now there's a challenge for you!)

**Comment by phax** [comment]
Would you please be so kind and open an issue for this. It looks odd if I open all the issues myself :) Thanks!!!

**Comment by phax** [comment]
If you are on the HEAD revision you can try the `smp.publicurl` property and tell me if it works for you (see https://github.com/phax/peppol-smp-server/wiki/Configuration#smp-serverproperties)
