### ISSUE TITLE
Service Group could not be created error

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-smp-server#64]
Currently we are having an issue on our SMP that is linked to the SMK.  When we create a service group, we get an error that the service group could not be created.  

Turns out that the service is actually created in the SMK, but the SMP thinks that it has not been created.  

We actually came up with a workaround to then turn off the SMK link, create the service group in the SMP, and then turn the link to the SMK back on.

**Comment by phax** [comment]
Hi, can you please send me the respective catalina*.out file of the day where that happened?
Is it possible that you have 2 instances running that operate on the same data directory on disk?

**Comment by phax** [comment]
Do you have any update on this topic? I haven't received any files so I'm having a hard time with "guessing only" :(

**Comment by phax** [comment]
Closed because lack of information
