### ISSUE TITLE
Inside the docker container in /usr/local/tomcat/logs directory there is no Catalina.out file

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-smp-server#66]
I believe that you use log4j2 for logging and a Console Appender.  That should mean that the logged messages go to Catalina.out.  For some reason there is no such file in the logs directory.  The catalina.sh file seems to have code to setup catalina.out:

if [ -z "$CATALINA_OUT" ] ; then
  CATALINA_OUT="$CATALINA_BASE"/logs/catalina.out
fi

but there is no file catalina.out and $CATALINA_OUT is empty.

How can I get the peppol-smp-server to log to catalina.out?

**Comment by phax** [comment]
To check the logs use `docker logs phoss-smp` - there is no catalina.out file

**Comment by phax** [comment]
See also https://github.com/docker-library/tomcat/issues/16

**Comment by dhixon** [comment]
I guess you are saying "working as designed".   I can indeed get a log of the console with your messages in it using the docker logs command.  I will close this issue.
