### ISSUE TITLE
HC Consistency check error

### ISSUE THREAD

**Issue by emilbokenstrand** [phax/peppol-smp-server#76]
Greetings,

When clicking Check DNS state on Service groups I get the following error (running 5.0.6):

javax.servlet.ServletException: java.lang.IllegalStateException: HC Consistency check error: Table with ID service_groupscheckdns body row #2 has 5 cells but was expecting 4 cells
	com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler._onException(XServletHandlerToSimpleHandler.java:103)
	com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler.onRequest(XServletHandlerToSimpleHandler.java:255)
	com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:337)
	com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:515)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:570)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.helger.web.servlets.scope.AbstractScopeAwareFilter.doHttpFilter(AbstractScopeAwareFilter.java:83)
	com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:538)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)
	com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:183)
	com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66)

root cause

java.lang.IllegalStateException: HC Consistency check error: Table with ID service_groupscheckdns body row #2 has 5 cells but was expecting 4 cells
	com.helger.html.hc.config.HCConsistencyChecker.consistencyError(HCConsistencyChecker.java:53)
	com.helger.html.hc.html.tabular.AbstractHCBaseTable._checkConsistency(AbstractHCBaseTable.java:355)
	com.helger.html.hc.html.tabular.AbstractHCBaseTable.checkInternalConsistency(AbstractHCBaseTable.java:408)
	com.helger.html.hc.html.tabular.AbstractHCBaseTable.onConsistencyCheck(AbstractHCBaseTable.java:416)
	com.helger.html.hc.impl.AbstractHCNode.consistencyCheck(AbstractHCNode.java:249)
	com.helger.html.hc.render.HCRenderer.lambda$prepareForConversion$64c3629$1(HCRenderer.java:150)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:77)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper._recursiveIterateTree(HCHelper.java:81)
	com.helger.html.hc.HCHelper.iterateTree(HCHelper.java:127)
	com.helger.html.hc.render.HCRenderer.prepareForConversion(HCRenderer.java:129)
	com.helger.photon.core.app.html.AbstractHTMLProvider.createHTML(AbstractHTMLProvider.java:178)
	com.helger.photon.core.app.html.PhotonHTMLHelper.createHTMLResponse(PhotonHTMLHelper.java:114)
	com.helger.photon.core.servlet.AbstractApplicationXServletHandler.handleRequest(AbstractApplicationXServletHandler.java:82)
	com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler.onRequest(XServletHandlerToSimpleHandler.java:240)
	com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:337)
	com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:515)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:570)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.helger.web.servlets.scope.AbstractScopeAwareFilter.doHttpFilter(AbstractScopeAwareFilter.java:83)
	com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:538)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)
	org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)
	com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:183)
	com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66)

Hope the above log will help!

Thanks

/Emil

**Comment by phax** [comment]
@emilbokenstrand  thanks for pointing that out.
That error only occurs in your locally compiled version - right? It only happens if `global.debug` is set to `true` in the `webapps.properties` file!
I think that was already fixed in https://github.com/phax/peppol-smp-server/commit/1486b9266f7527a36c273653afecc38a59558fe0 - please confirm that you have the most current version running.

**Comment by emilbokenstrand** [comment]
Thanks Philip.

I was running 5.0.6 but when pulling the trunk it worked!

**Comment by phax** [comment]
Ah okay - thanks for reminding me that this is part of 5.0.6 :( Will do 5.0.7 soon anyway
