### ISSUE TITLE
Error invoking ph AJAX function [success]!

### ISSUE THREAD

**Issue by robrechtD** [phax/peppol-smp-server#77]
We receive the following error popup when trying to display the endpoints page.
![image](https://user-images.githubusercontent.com/15961871/46800467-0cc73c80-cd58-11e8-9e8c-ec0173458c7c.png)

What is this caused by and how is it solved?
Any steps that I can take?
We are on version 5.0.6

**Comment by phax** [comment]
Did you compile the version yourself, or did you use a pre-build binary?
Are you running it behind an explicit Webserver?

**Comment by robrechtD** [comment]
We are running a pre-build binary without an explicit webserver

**Comment by phax** [comment]
Do you seen anything weird in the server logs or the browser logs?

**Comment by phax** [comment]
Can I send you an invite to Slack so that we can chat? Find my email address in the pom.xml or use firstname@lastname.com for email exchange

**Comment by robrechtD** [comment]
I will send you an email for further communication

**Comment by phax** [comment]
After log analysis and retesting the issues has disappeared. Was Chrome, with Tomcat 8.5.11 and Java 8_102 on Windows.
