### ISSUE TITLE
Unable to delete service groups

### ISSUE THREAD

**Issue by robrechtD** [phax/peppol-smp-server#79]
I am unable to delete a servicegroup, I have tested both with and without endpoints registered to this service group. I receive the message for a successful deletion but the group remains.
![image](https://user-images.githubusercontent.com/15961871/47091430-27505880-d225-11e8-83d7-ba872daaf6b6.png)
![image](https://user-images.githubusercontent.com/15961871/47091450-333c1a80-d225-11e8-9418-d40795c3891c.png)
I am on version 5.0.6

**Comment by phax** [comment]
You have the SQL backend right?

**Comment by robrechtD** [comment]
That is right

**Comment by phax** [comment]
There is an issue, that the errors are not propagated correctly for the SQL backend. This is already fixed in the current 5.0.7 SNAPSHOT
Can you try the current SNAPSHOT or do you need to wait for a release?

**Comment by robrechtD** [comment]
I will try the 5.0.7 snapshot, where can I find it?

**Comment by phax** [comment]
The latest one is SNAPSHOT 60 in the folder https://oss.sonatype.org/content/repositories/snapshots/com/helger/peppol-smp-server-webapp-sql/5.0.7-SNAPSHOT/ (the last one)

**Comment by robrechtD** [comment]
The issue persists on the latest snapshot unfortunately

**Comment by phax** [comment]
So you have a success message but the service group is still there. Weird. Do you see any error in the catalina.out file?

**Comment by robrechtD** [comment]
This is the only error I can spot

18-Oct-2018 11:53:43.566 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [com.sun.xml.ws.api.server.ThreadLocalContainerResolver$1] (value [com.sun.xml.ws.api.server.ThreadLocalContainerResolver$1@6150f015]) and a value of type [com.sun.xml.ws.api.server.Container.NoneContainer] (value [com.sun.xml.ws.api.server.Container$NoneContainer@236bc12]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by phax** [comment]
That's the classical shutdown error. No way to work around it.
Is your SML connection enabled?
When trying to query 9914:test on SMK I get a 503 error: https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=9914%3Atest&sml=auto&action=perform

Did you potentially register the participant before enabling SML and now you want to delete it with SML being enabled?

**Comment by phax** [comment]
When opening `http://smp-test.dynatos.be/iso6523-actorid-upis%3A%3A9914%3Atest` I only see an empty service group without any endpoint. Can you eventually share screen via Skype or so?

**Comment by robrechtD** [comment]
This is correct, I have deleted its endpoints. 
in http://smp-test.dynatos.be/iso6523-actorid-upis%3A%3A9910%3Ahu13177980 some endpoints are still registered and this participant returns the same 503 error when queried

**Comment by phax** [comment]
Okay, if I open http://smp-test.dynatos.be/iso6523-actorid-upis%3A%3A9910%3Ahu13177980/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspecification%3Aubl%3Aschema%3Axsd%3AApplicationResponse-2%3A%3AApplicationResponse%23%23urn%3Awww.cenbii.eu%3Atransaction%3Abiitrns071%3Aver2.0%3Aextended%3Aurn%3Awww.peppol.eu%3Abis%3Apeppol36a%3Aver1.0%3A%3A2.1 manually in the browser it works.

If I use the generated name http://B-33c4ab5463f5ad9dcc202467a15edca8.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/iso6523-actorid-upis%3A%3A9910%3Ahu13177980/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspecification%3Aubl%3Aschema%3Axsd%3AApplicationResponse-2%3A%3AApplicationResponse%23%23urn%3Awww.cenbii.eu%3Atransaction%3Abiitrns071%3Aver2.0%3Aextended%3Aurn%3Awww.peppol.eu%3Abis%3Apeppol36a%3Aver1.0%3A%3A2.1 I get the 503 also in the browser.

The reason is most likely, that your proxy server does not handle the dynamic addressing as e.g. outlined at https://github.com/phax/peppol-smp-server/wiki/Running#running-behind-an-httpd ??

**Comment by robrechtD** [comment]
We are not running our smp server behind a proxy though. 
The issue also only occurred after upgrading and downgrading to/from 5.0.7, in the downgrade process I replaced all files generated by the deployment process to the original files.

**Comment by phax** [comment]
Try opening http://DYNATOS-TEST-SMP.publisher.acc.edelivery.tech.ec.europa.eu - it also delivers an error. Is the page shown, the one of your Tomcat?

**Comment by robrechtD** [comment]
This page, as well as http://b-33c4ab5463f5ad9dcc202467a15edca8.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/ refers to the correct ip adress but this page does not look like a tomcat page?

**Comment by phax** [comment]
In the Tomcat-Server you can configure pages for specific error codes like 404 or 500 (I think both in `serverl.xml` and in `webapp.xml`). To me it looks more like you have some upfront server that processes requests before they reach your Tomcat. Does that make sense?

**Comment by phax** [comment]
I could identify the issue that no proper error message is shown. So now that happens but it still the question why the deletion does not work. I will improve logging

**Comment by robrechtD** [comment]
Concerning the issue of the smk error, our server is hosted by a third party and I am currently in contact with them about possible changes which may have caused the issue.

**Comment by robrechtD** [comment]
The smk error has been fixed. A new url has been recently added to our server and the catch all rule was deleted. This rule has now been restored. 
The only issue that remains is the original issue where I cannot delete a service group.

**Comment by phax** [comment]
I increased logging in the 5.0.7 version. Can you please retry the latest 5.0.7 SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/com/helger/peppol-smp-server-webapp-sql/5.0.7-SNAPSHOT/ and check the log files for errors?

**Comment by phax** [comment]
So it is an issue with the identifier not being able to be deleted in the SML. CEF supported was contacted.
