### ISSUE TITLE
Propagation of SML errors does not work while deleting service groups (REST)

### ISSUE THREAD

**Issue by mgu7** [phax/peppol-smp-server#80]
Propably from 2 days 2 of SML servers (TEST environment) are dead and it cause a a lot of problems in SMP operatation. During  creating  a new group we get the HTTP code 400 and it is acceptable. Unfortunately, when deleting a service group - despite errors in contact with SML - the status is OK (HTTP code 200). IN SMP the group is not deleted.

**Comment by phax** [comment]
I will check with the latest version, but I guess that was fixed in the latest 5.0.8 release

**Comment by phax** [comment]
Okay thanks for checking. I was at a Peppol F2F and found no time yet to check.

**Comment by phax** [comment]
Delete errors are now propagated properly.
