### ISSUE TITLE
Max response time for REST operations

### ISSUE THREAD

**Issue by mgu7** [phax/peppol-smp-server#81]
Could you explain what may be the maximum response time can be for REST operations requiring contact with SML. In the case of errors, SML operations are repeated with different timeout. What is the maximum waiting time for an SML response.

**Comment by phax** [comment]
There is basically the connection timeout from SMP to SML. This is configured via the `sml.connection.timeout.ms` setting (in milliseconds).
And there is the read timeout - that is how long to wait for a response. This is configured via the `sml.request.timeout.ms` setting (also in milliseconds).
See the configuration documentation at https://github.com/phax/peppol-smp-server/wiki/Configuration#smp-serverproperties
hth

**Comment by mgu7** [comment]
I thought so too, but something does not agree. I have uncommented the standard values
(sml.connection.timeout.ms = 5000, sml.request.timeout.ms = 20000) that is 5 and 20 seconds respectively. But during tests, the first repetitions happen after 2 or 3 minutes, the worst time I observed so far was 28 minutes. There is a examle from catalina.log

[2018-11-02T13:29:12,012] [SMP-SERVER] [WARN ] [ajp-nio-8209-exec-128] Callback: 1658918 ms; transaction: true; Execution of callable in transaction took too long: com.helger
java.lang.Exception: null

**Comment by phax** [comment]
If nothing is configured, there are default values in class `WSClientConfig` that should limit the time. These default values are 5 seconds for connection timeout and 5 seconds for read timeout.
Do you have some special JAX-WS configuration (system properties?) in place? Do you have some special JAXWS libraries in your (endorsed) classpath? Do you have a proxy server that defines it's own values?

**Comment by mgu7** [comment]
The SMP server is running as apache-tomcat-8.5.13 application. The SMP server is accessible via Apache 2.4 with mod_jk. All in default configuration. Tests are performed using the curl application. Does it affect the fact that sometimes SMP waits half an hour before repeating the SML operation?

**Comment by phax** [comment]
Well the application itself does not perform a retry automatically. I think this is a database issue! The text `Execution of callable in transaction took too long` indicates that time is spent in the DB transaciton layer!

**Comment by mgu7** [comment]
I have changed the backend to from mysql to xml and the results are similar. I have attached 2 logs from create and delete the service group. Yesterday I have found the operation which have been repeated only after 4,5 hour (the record).

[cat147_create.log](https://github.com/phax/peppol-smp-server/files/2552693/cat147_create.log)
[cat187_delete.log](https://github.com/phax/peppol-smp-server/files/2552694/cat187_delete.log)

**Comment by phax** [comment]
Ah okay - thanks. I know what it is :)
This is a known issue on the Java random generator - see e.g. https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html

So try adding `-Djava.security.egd=file:/dev/urandom` to your application server configuration

**Comment by mgu7** [comment]
That is it!!!
Thanks a lot.
