### ISSUE TITLE
PEPPOL directory support problem?

### ISSUE THREAD

**Issue by mgu7** [phax/peppol-smp-server#84]
When this functionality is enable, all business cards transaction are finished  in interface OK but in catalina log is an connection error:
[2018-11-06T11:40:07,868] [SMP-SERVER] [ERROR] [ajp-nio-8109-exec-9] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::9945:test03 -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$5f881514$1(PDClient.java:67)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

Could you check it?

**Comment by phax** [comment]
Try to add the following line in your `pd-client.properties` file:
```
https.hostname-verification.disabled = true
```

**Comment by mgu7** [comment]
I have this line from the beginning. This not work.

**Comment by phax** [comment]
Okay thanks - was just to ensure the basic constraints are fulfilled. Which PEPPOL Directory URL do you have configured in your SMP:
![grafik](https://user-images.githubusercontent.com/196219/48071885-a3faa500-e1db-11e8-8f5a-a814c83cab1b.png)

**Comment by mgu7** [comment]
I try 2 settings:
https://directory.peppol.eu
https://test-directory.peppol.eu

Both URL point to the same IP.
The result is the same

**Comment by mgu7** [comment]
One more.
The result is the same in the test and productive environment.

**Comment by phax** [comment]
The same IP is okay (they indeed run on the same server). Have you configured a proxy server?

**Comment by mgu7** [comment]
No proxy server.

**Comment by phax** [comment]
Please check if anything from https://stackoverflow.com/a/6353956 helps

**Comment by mgu7** [comment]
Is the address "https://directory.peppol.eu" is correct?

The server in that address provides the certificate with DNS names:
 test.erechnung.gv.at, test.erb.gv.at, test.e-rechnung.gv.at

So the connection to https://directory.peppol.eu is finished with SSL error (in the curl utility I may break it with -k option".
I temporary change the address to https://test.erechnung.gv.at and the connection phase has been established but but update operation has failed on timeout. I attached the logs from update directory with settings: https://directory.peppol.eu, and https://test.erechnung.gv.at

[cat1.log](https://github.com/phax/peppol-smp-server/files/2556495/cat1.log)
[cat2.log](https://github.com/phax/peppol-smp-server/files/2556496/cat2.log)

**Comment by phax** [comment]
Yes, `https://directory.peppol.eu` is correct.
We are aware that there is an issue with the TLS certificates - there are none, so using "-k" is OK atm. OpenPEPPOL is working to find a solution.
Don't use `test.erechnung.gv.at` because this is a different application. Basically by disabling the hostname check in the PD client file (see above) everything should be okay. I assume that you are not trusting the respective root certficiate from test.erechnung.gv.at.... I will prepare an updated truststore and link it here

**Comment by mgu7** [comment]
This is probable java issue. When I set "https.hostname-verification.disabled = false" I have got another error abut certificate names, so that setting is working but is not enough. We are using java 1.8.0_181.
When I set a previously incorrect URL "https://test.erechnung.gv.at" the connection SSL phase has been established. Have you any suggestions? Maybe the older java version?

I have attached log with "-Djavax.net.debug=all".
[cat.zip](https://github.com/phax/peppol-smp-server/files/2557067/cat.zip)

**Comment by phax** [comment]
I think the ZIP File contains only the old log entries (cat147_create.log and cat187_delete.log)

**Comment by mgu7** [comment]
Sorry, that should be OK.

[cat2.zip](https://github.com/phax/peppol-smp-server/files/2557127/cat2.zip)

**Comment by phax** [comment]
Do you have a PEPPOL PKI V3 SMP certificate???

**Comment by mgu7** [comment]
Yes
 In certificate information:
"You are currently using a PEPPOL pilot v3 certificate!"

**Comment by phax** [comment]
Thanks - maybe we have a small configuration issue on our side, that the V3 certificates are not yet supported as Client Certificates. So please stay tuned, I will keep you posted when I know more.

**Comment by mgu7** [comment]
Thanks, I will be waiting

**Comment by mgu7** [comment]
The error code has changed to: unknown ca
The result is the same without or with the file: complete-truststore.jks you sent me yesterday.

[2018-11-08T09:35:34,921] [SMP-SERVER] [INFO ] [ajp-nio-8209-exec-2] After HTTP call: PUT -- com.helger.httpclient.HttpDebugger.afterRequest(HttpDebugger.java:99)
javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca

**Comment by phax** [comment]
Thanks for testing - please try one more time

**Comment by phax** [comment]
Please try again - I think it will work now (root CAs were missing). Sorry for the inconvenience

**Comment by phax** [comment]
Thanks for constantly testing! It was simply an issue, that the SMP root certificates were not trusted on httpd level. Tricky one :smile:
