### ISSUE TITLE
Error in SQL script

### ISSUE THREAD

**Issue by paulm76** [phax/peppol-smp-server#86]
Hi,

I realized that both backup scripts had an error in the data type of the `requirebusinesslevelsignature` column in the `smp_endpoint` table. In the script the column is defined with a `tinyint` and it's a `boolean` in the implementation. I understand why you choose a `tinyint` to represent a `boolean` but it seems postgresql is not able to auto convert the type. I know you use mysql and I don't know if it auto convert so I prefer post this issue. Finally I changed the type in postgresql and all work fine.
Feel free to close the issue because I already solved the problem.

I have version 5.0.8 of the SMP and version 10.4 of postgresql.

Best regards,

Paul

**Comment by phax** [comment]
I tried modifying the type in the MySQL Workbench from "TINYINT(1)" to "BOOLEAN" without any effect. Some googling brought me to https://stackoverflow.com/a/289759/15254:
> Bool, Boolean: These types are synonyms for TINYINT(1). A value of zero is considered false. Non-zero values are considered true.
I created a new SQL file that uses `BOOLEAN` internally - thanks for pointing that out
