### ISSUE TITLE
Refreshing Peppol Directory information

### ISSUE THREAD

**Issue by mgu7** [phax/peppol-smp-server#88]
In Peppol Directory it is possible to check the list of serviced documents by the service group. But changing this list in SMP does not force change in Peppol Directory. In the web interface is possibility to force refresh information in Peppol Directory. Is there any possibility of forcing this change with the REST mechanism (other than changing the whole Business Card).

**Comment by phax** [comment]
Yes there is. When you click the button in the button, the following happens:
1. SMP sends a REST request to PEPPOL Directory containing the participant identifier. The SMP client certficate must be used, when the PD server uses https.
2. PD queues the request
3. PD creates the URL of the SMP based on the participant identifier and queries the respective /businesscard

An automatic update to the PEPPOL Directory if a document type of a service group changes, is currently not forseen. But the Directory updates the entries automatically every 2 weeks.

So what do you need?

**Comment by phax** [comment]
@mgu7 - any news on this?

**Comment by mgu7** [comment]
We accepted that it works like that. It could be better but hard. Sometimes it would be useful to use the 'Update directory' operation via the REST interface (as it is in the WEB interface), but without it you can work around it.
Thank you for your interest.

**Comment by phax** [comment]
Thanks for your feedback.
1. I created #94 to explicitly add an option to update the Directory when something document type related changes
1. Do I understand it correctly: you want a new REST API that just triggers the update from SMP to the Directory for a specific Service Group?

**Comment by mgu7** [comment]
If the proposal from point 1 will be implemented, the point 2 is not necessary.

**Comment by phax** [comment]
I would like to go for option 1. I'm closing this, please follow #94 for the progress. Thx.
