### ISSUE TITLE
PD not update

### ISSUE THREAD

**Issue by paulm76** [phax/peppol-smp-server#89]
Hi Philip

I am conducting some tests with the SMP and it is not working well.
I tried to register a new participant from our platform to the SMP. It worked and the SML is update.
After I tried to add the business card. The SMP is update but not the SML.
I don't understand why the first instruction work and the second not.
Have you any idea ?

The screenshot of the SMP : 
![smp_view](https://user-images.githubusercontent.com/22341212/49948490-db075900-fef3-11e8-8edf-b988b27994d1.png)

The screenshot of the directory : 
![vefa_view](https://user-images.githubusercontent.com/22341212/49948517-e9ee0b80-fef3-11e8-8454-6e7f9486147e.png)

Best regards,

Paul

**Comment by paulm76** [comment]
Finally it may not be a problem because I did a lookup using your tool (http://peppol.helger.com) and I found all the information I sent...
I am more and more disappointed

**Comment by phax** [comment]
Hello Paul,
only each "Service Group" is registered (once) at the SML, and once you create the Busines Card, also on the PEPPOL Directory (which is either http://directory.peppol.eu or http://test-directory.peppol.eu - depending on your setup).
I have no impact on the VEFA Tool - and I think it is the same as my page (peppol.helger.com) - a lookup tool. But not an OFFICIAL Peppol tool.

There are several configuration issues with your setup:
* Please set "global.debug" to "false"
* Please set "smp.publicurl" to your correct public URL
Note: I got this information from http://b-648ac7e9d64176da90be31faff1d2227.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/smp-status/

By calling http://b-648ac7e9d64176da90be31faff1d2227.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/iso6523-actorid-upis::9918:810418052 I can see, that the wrong URL is returned - that's (one reason) why your identifier is not in the PEPPOL Directory.

Please make this changes, restart the Tomcat, go to the menu item "Business Cards" and create one for your 9918:810418052 identifier.
You can check if it worked by opening http://b-648ac7e9d64176da90be31faff1d2227.iso6523-actorid-upis.acc.edelivery.tech.ec.europa.eu/businesscard/iso6523-actorid-upis::9918:810418052

hth, Philip

**Comment by paulm76** [comment]
Hi Philip,

I change the "global.debug" and "smp.publicurl" parameters.
I wasn't able to find the returned URL. How can I do this ?
The service group still not appear in the directory.

Br, Paul

**Comment by phax** [comment]
Hi Paul,
happy new year. Did you manage to resolve this issue?
Thanks.

**Comment by paulm76** [comment]
Hi Philip,

Happy new year !
I am sorry I didn't notify you I don't manage anymore the SMP implementation.
It was my mission during my internship and a collaborator pick up the mission. 
I will ask him if he solve the problem and I come back to you.

Best regards,

Paul

**Comment by paulm76** [comment]
Hi Philip,

I do not have news from my colleagues so I close the issue.

Best regards,

Paul
