### ISSUE TITLE
Configuration parameter for domain name

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#9]
It would be useful to have a parameter in the configuration files to specify the FQDM where the server should be hosted, to avoid forcing it in a proxy configuration

**Comment by phax** [comment]
If you are on the HEAD revision you can try the `smp.publicurl` property and tell me if it works for you (see https://github.com/phax/peppol-smp-server/wiki/Configuration#smp-serverproperties)

**Comment by phax** [comment]
This is now released in version 4.1.0 and should work as expected.

**Comment by phax** [comment]
Hi Oskar!
Do you have an update for me, whether it works as expected?
Thanks

**Comment by OskarD** [comment]
Not yet @phax sorry! I really appreciate your dedication and quick answers, and I wish I could be of more help, but I am very busy right now with other projects. I will let you know once I have tried it though!
