### ISSUE TITLE
Security Issue:  Admin userid and password not stored in database causing reset to default whenever docker container is replaced.

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-smp-server#90]
The Admin user ID and password are not stored in the database with the rest of the user ID's and passwords.  For this reason, they are reset to default values resulting in a security vulnerability until they are changed.  If the DevOps personnel forget to change the Admin ID every time they rebuild the container, that can result in a big security vulnerability.  All a hacker has to do is use Google Hacking Query allintext:"phoss smp" \| allintext: "default password" to discover the default user id and password and break into the system.

**Comment by phax** [comment]
Hi David,
you are absolutely right. That's why the page "Tasks/problems" contains an error message `Please change the password of the default user admin@helger.com!` if the password was not changed yet. This was added on January 3rd 2017, so for release 5.0.2.
hth, Philip

**Comment by phax** [comment]
What would that change? The password of the GUI user is stored as a hash value in the file system (by default using PBKDF2 algorithm with 1000 iterations and 48 bytes hash value).
The respective file (security/user.xml) should never be reachable via the web server, as such it makes no difference whether it is in the DB or in a file.
The database contains "only" the REST API users.

**Comment by dhixon** [comment]
My issue is that we use Docker containers, and because of that when we upgrade to a new level of your software we generate a new container and everything that was stored on the local file system inside the previous container is lost, including the GUI user.  If all the configuration information is stored in the database, then we simply build a new container and start it.

**Comment by phax** [comment]
Ah okay - thanks for the clarification.
As there are a lot of things stored outside the database this is not really an option. I really suggest storing data outside the Docker image. Backwards compatibility is important, so you could also backup the old data before updating, and just reusing this data with the new versions.

**Comment by dhixon** [comment]
Is the data in one directory, or subtree?  What is the path?

**Comment by phax** [comment]
It's one directory and all of its contents (so recursive). The path is specified in `webapps.properties`.
