### ISSUE TITLE
PEPPOL Directory not updating

### ISSUE THREAD

**Issue by tramperdk** [phax/peppol-smp-server#91]
Hi @phax ,

I seem to have this problem with my installation as well.
Worked flawlessly with `https.hostname-verification.disabled=true` on our TEST environment, but on production I get the following error:

`[2019-01-11T10:00:01,080] [SMP-SERVER] [ERROR] [https-jsse-nio-443-exec-1] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::0088:5790002044496 -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$5f881514$1(PDClient.java:67)
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

I've configured the truststore you specified earlier as well, no change.
I also configured `smp.publicurl` even though it didn't seem like it was needed ( Was commented out by default ).

Our production which is configured with a V3 Production certificate while our TEST ( Which is working ) was established a while ago and is using a V2 Pilot certificate.

Reading this issue (https://github.com/phax/peppol-smp-server/issues/84) I'm curious if some of this is related to my issue as well since it seems pretty spot on :)

Our participant information on your website:
https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0088%3A5790002044496&sml=auto&action=perform

**Comment by phax** [comment]
Hi Simon,
you need the `https.hostname-verification.disabled=true` entry on production as well.
Currently the Directory hosting is on a server where there is no suitable https certificate available.
I'm working with OpenPEPPOL on a migration to a proper server, where a proper certificate will be present - sorry for the inconvenience.
BR, Philip

**Comment by phax** [comment]
Hi Simon,
We had an httpd configuration issue with accepting PKI v3 certificates as TLS client certificates, but that was resolved and should work for all clients now.

Reasons for `handshake_failure` according to https://stackoverflow.com/a/6353956/15254 can be:
> * Incompatible cipher suites in use by the client and the server. This would require the client to use (or enable) a cipher suite that is supported by the server.
> * Incompatible versions of SSL in use (the server might accept only TLS v1, while the client is capable of only using SSL v3). Again, the client might have to ensure that it uses a compatible version of the SSL/TLS protocol.
> * Incomplete trust path for the server certificate; the server's certificate is probably not trusted by the client. This would usually result in a more verbose error, but it is quite possible. Usually the fix is to import the server's CA certificate into the client's trust store.
> * The cerificate is issued for a different domain. Again, this would have resulted in a more verbose message, but I'll state the fix here in case this is the cause. The resolution in this case would be get the server (it does not appear to be yours) to use the correct certificate.

We're accepting TLS 1.0, 1.1 and 1.2 but not 1.3 (see https://www.ssllabs.com/ssltest/analyze.html?d=directory.peppol.eu&hideResults=on - ignore the mismatch error).

Can you please send me your SMP-Status (to be received from your /smp-status/ URL) - thanks. My email address can be found in the pom.xml

hth

**Comment by tramperdk** [comment]
@phax sorry for the late reply.

Visting https://www.ssllabs.com/ssltest/viewMyClient.html shows our server is compatible with all TLS versions and none of SSL.

Running a test on directory.peppol.eu i see TLS versions except 1.3 is enabled as you said.
We also share some ciphers, the first cipher in the cipher suggestion list is `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`

If anyone else is having trouble getting to smp-status, it's important to keep the trailing '/'.
I've sent the results to you per mail @phax

**Comment by phax** [comment]
Thanks for the information - I got them.
It contains no obvious misconfiguration, so I'm happy :)
Stupid question: you put the `https.hostname-verification.disabled` setting in your `pd-client.properties` file, right (see https://github.com/phax/peppol-directory/#pd-client for details)? This has no effect when put in `smp-server.properties`....

**Comment by phax** [comment]
Well, directory.peppol.eu and test-directory.peppol.eu run on exactly the same machine, therefore having the same crud TLS setup ;-)
Since the Directory is running on https, you are asked to provide a client certificate, which will be your SMP certificate. As stated in https://github.com/phax/peppol-smp-server/issues/84#issuecomment-437105519 this worked for mgu7 in test AND production, so I doubt that this is a configuration issue on our side (httpd etc.).

Did you modify anything on your truststore on Java level? Did you potentially configure one via the `javax.net.ssl.trustStore` system property?

**Comment by tramperdk** [comment]
Morning @phax,

No, I did not modify anything on Java level, it's a completely clean `JRE 1.8.0_191` installation.

Tomcat starts with these parameters:
`-Dcatalina.home=C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0
-Dcatalina.base=C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0
-Djava.io.tmpdir=C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\temp
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-Djava.util.logging.config.file=C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\conf\logging.properties`

**Comment by tramperdk** [comment]
@phax 

I checked the trust store earlier, everything seems to be in order, I have some System Signer CA and System Secure Site CA listed, but it all seems to be the usual GlobalSign etc.

Considering I do not know AdoptOpenJDK I'm going to say no.

It's a completely blank machine following your instructions on your Wiki I'm afraid.

When you say that our SMP certificate is in use, do you mean the public certificate?
I could suspect I might be exporting the public certificate wrong, which in return could maybe lead to the handshake error.

On both the Keystore tab and Peppol directory keystore tab we have the following error:
`The private key should be a chain of 3 certificates but it has 2 certificates. Please ensure that the respective root certificates are contained!`
The only reason I've not mentioned this is that we have that error on TEST as well ( Where things work ) - although there it seems to be only one certificate.

Just to make sure I create the certificate store the way you would have wanted, how do I begin if I have the PFX I received from OpenPEPPOL?

**Comment by phax** [comment]
Thanks for the email.
That might exactly be the issue here.
Can you please add the respective root certificates into your certificate?
Ideally the keystore consists of exactly one entry which itself is a chain of 3 entries (SMP private key, SMP Root certificate, Root certificate)  - see https://github.com/phax/peppol-smp-server/wiki/Certificate-setup for some guidance on this.

Btw. OpenJDK from https://adoptopenjdk.net/ are pre-build binaries of OpenJDK because of the Oracle licensing change...

**Comment by tramperdk** [comment]
@phax 

I'll try to see if I can do something with that guide.

Although I do not have a .key nor a .cer, the new OpenPEPPOL certificate retreival system results in a single .pfx file.

**Comment by phax** [comment]
I'm using Portecle from http://portecle.sourceforge.net to look into my keystores (OSS).
.pfx is I think a single certificate - unfortunately my employee did not receive a production v3 certificate (shame on us), so I'm lacking the exact information on what is inside :(

Nevertheless the respective truststores (incl. the root certficates) can be found at https://github.com/phax/peppol-commons/tree/master/peppol-commons/src/main/resources/truststore/2018 - the password to all of them is "peppol".

**Comment by phax** [comment]
Now I'm really stuck.
Are you using some kind of proxy server or central TLS termination service (like Bluecoat) that could potentially interfere?
I suggest you add ` -Djavax.net.debug=all` to your Tomcat commandline and we investigate together what the issue is.... sorry.

And thanks for the guideline - I will use this as the basis for the v3 rules once I have a certificate for verification :)

**Comment by tramperdk** [comment]
@phax 

No problem :)

I'll add the command line, flush the logs and send them to you 👍 
We are hosted on a vCloud platform and have an "EdgeGateway" in front that functions as a reverse proxy in this scenario.

Please note TEST that is functioning correct also has a similar setup, although it's being reverse proxied by an Azure Application Gateway

**Comment by phax** [comment]
Line 19864: accepted certificates are:
```
Cert Types: RSA, DSS, ECDSA
Supported Signature Algorithms: SHA512withRSA, Unknown (hash:0x6, signature:0x2), SHA512withECDSA, SHA384withRSA, Unknown (hash:0x5, signature:0x2), SHA384withECDSA, SHA256withRSA, SHA256withDSA, SHA256withECDSA, Unknown (hash:0x3, signature:0x1), Unknown (hash:0x3, signature:0x2), Unknown (hash:0x3, signature:0x3), SHA1withRSA, SHA1withDSA, SHA1withECDSA
Cert Authorities:
<CN=PEPPOL Root CA - G2, O=OpenPEPPOL AISBL, C=BE>
<CN=PEPPOL Root CA, O=NATIONAL IT AND TELECOM AGENCY, C=DK>
<CN=PEPPOL SERVICE METADATA PUBLISHER CA - G2, O=OpenPEPPOL AISBL, C=BE>
<CN=PEPPOL Root TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE>
<CN=PEPPOL SERVICE METADATA PUBLISHER CA, O=NATIONAL IT AND TELECOM AGENCY, C=DK>
<CN=PEPPOL Root TEST CA, OU=FOR TEST PURPOSES ONLY, O=NATIONAL IT AND TELECOM AGENCY, C=DK>
<CN=PEPPOL SERVICE METADATA PUBLISHER TEST CA - G2, OU=FOR TEST ONLY, O=OpenPEPPOL AISBL, C=BE>
<CN=PEPPOL SERVICE METADATA PUBLISHER TEST CA, OU=FOR TEST PURPOSES ONLY, O=NATIONAL IT AND TELECOM AGENCY, C=DK>
```
So both your issuer and your root certificate's subject is contained in that list.

**Comment by ssinatti** [comment]
Good morning Philip,

Same problem from IntercentER SMP. 

1. ROOT CA imported on my JDK8 cacerts 
2. I've tried to disable the hostname verification 

Still have the issue : 

http-bio-8090-exec-7, READ: TLSv1.2 Alert, length = 26
Padded plaintext after DECRYPTION:  len = 2
0000: 02 28                                              .(
http-bio-8090-exec-7, RECV TLSv1.2 ALERT:  fatal, handshake_failure
%% Invalidated:  [Session-7, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
%% Invalidated:  [Session-8, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
http-bio-8090-exec-7, called closeSocket()
http-bio-8090-exec-7, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
http-bio-8090-exec-7, called close()
http-bio-8090-exec-7, called closeInternal(true)
[2019-03-25T10:22:34,778] [SMP-SERVER] [ERROR] [http-bio-8090-exec-7] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::9906:it12312312312 -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$5f881514$1(PDClient.java:65)

I suspect that our problem is that the keystore used for the peppol id registration (it works correctly) is not PKv3 aligned so the PD does not work.

Thank you in advance.

Stefano
