### ISSUE TITLE
InternalErrorFault when trying to change SML registration

### ISSUE THREAD

**Issue by SilvanoSorrentino** [phax/peppol-smp-server#92]
Hi,
I am using version 5.0.8, and I am trying to register to a new SML (the old configuration was wrong and I was not pointing to the correct SML).

I was already registered in the old SML, so let's call this OLD_SML and call the new one NEW_SML, so here are the steps I have followed:
- Administration / SML / SML Configuration / Copy OLD_SML Configuration (to create NEW_SML, that's been edited with the new URL)
- Administration / SML /  SML Registration / Delete SMP from SML (for OLD_SML)
- Administration / SML /  SML Configuration / Delete OLD_SML 
- Administration / SMP Settings -> make sure the "SML to be used" points to NEW_SML

All ok for now!

The next step is to register my SMP in NEW_SML, so I tried this:
- Administration / SML /  SML Registration / Register SMP at SML
But I got "internal-error-54" in return, with the following stacktrace:

`
com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Message part {http://busdox.org/serviceMetadata/locator/1.0/}CreateServiceMetadataPublisherService was not recognized.  (Does it exist in service WSDL?) Please see the server log to find more detail regarding exact cause of the failure.
1.: com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:193)
2.: com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:131)
3.: com.sun.xml.ws.client.sei.StubHandler.readResponse(StubHandler.java:253)
4.: com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:203)
5.: com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:290)
6.: com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:119)
7.: com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:92)
8.: com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:161)
9.: com.sun.proxy.$Proxy199.create(Unknown Source)
10.: com.helger.peppol.smlclient.ManageServiceMetadataServiceCaller.create(ManageServiceMetadataServiceCaller.java:187)
11.: com.helger.peppol.smlclient.ManageServiceMetadataServiceCaller.create(ManageServiceMetadataServiceCaller.java:150)
12.: com.helger.peppol.smpserver.ui.secure.PageSecureSMLRegistration._registerSMPtoSML(PageSecureSMLRegistration.java:200)
13.: com.helger.peppol.smpserver.ui.secure.PageSecureSMLRegistration.fillContent(PageSecureSMLRegistration.java:452)
14.: com.helger.peppol.smpserver.ui.secure.PageSecureSMLRegistration.fillContent(PageSecureSMLRegistration.java:70)
15.: com.helger.photon.uicore.page.AbstractWebPage.getContent(AbstractWebPage.java:160)
16.: com.helger.peppol.smpserver.ui.pub.SMPRendererPublic.getPageContent(SMPRendererPublic.java:259)
17.: com.helger.peppol.smpserver.ui.secure.SMPRendererSecure.getContent(SMPRendererSecure.java:205)
18.: com.helger.peppol.smpserver.ui.SMPLayoutHTMLProvider.fillBody(SMPLayoutHTMLProvider.java:70)
19.: com.helger.photon.core.app.html.AbstractSWECHTMLProvider.fillHeadAndBody(AbstractSWECHTMLProvider.java:99)
20.: com.helger.photon.core.app.html.AbstractHTMLProvider.createHTML(AbstractHTMLProvider.java:173)
21.: com.helger.photon.core.app.html.PhotonHTMLHelper.createHTMLResponse(PhotonHTMLHelper.java:114)
22.: com.helger.photon.core.servlet.AbstractApplicationXServletHandler.handleRequest(AbstractApplicationXServletHandler.java:91)
23.: com.helger.xservlet.handler.simple.XServletHandlerToSimpleHandler.onRequest(XServletHandlerToSimpleHandler.java:245)
24.: com.helger.xservlet.AbstractXServlet._invokeHandler(AbstractXServlet.java:344)
25.: com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:524)
26.: javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
27.: com.helger.xservlet.AbstractXServlet.service(AbstractXServlet.java:579)
28.: org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
29.: org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
30.: org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
31.: org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
32.: org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
33.: com.helger.web.servlets.scope.AbstractScopeAwareFilter.doHttpFilter(AbstractScopeAwareFilter.java:83)
34.: com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66)
35.: org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
36.: org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
37.: org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:538)
38.: org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:525)
39.: org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:462)
40.: org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
41.: org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
42.: com.helger.servlet.filter.CharacterEncodingFilter.doHttpFilter(CharacterEncodingFilter.java:187)
43.: com.helger.servlet.filter.AbstractHttpServletFilter.doFilter(AbstractHttpServletFilter.java:66)
44.: org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
45.: org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
46.: org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
47.: org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
48.: org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
49.: org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
50.: org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
51.: org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
52.: org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
53.: org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
54.: org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
55.: org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
56.: org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
57.: org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
58.: org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
59.: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
60.: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
61.: org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
62.: java.lang.Thread.run(Thread.java:748)
`

![immagine](https://user-images.githubusercontent.com/36923851/51250160-db34c180-1995-11e9-8be7-c4be0db6e8ad.png)

Also both the Update and Delete buttons do not work, with similar errors (code 56 and 55).

I also tried the Service Group / Check DNS State / Register in SML button, but I get a different error in response

![immagine](https://user-images.githubusercontent.com/36923851/51250234-0a4b3300-1996-11e9-95af-b3dad5f99a9c.png)

What can I try to register to NEW_SML? Any suggestion is welcome. 
Thank you!

**Comment by phax** [comment]
So the reason is the invalid SML URL. It should be only `https://acc.edelivery.tech.ec.europa.eu/edelivery-sml` without the `/manageparticipant` at the end

**Comment by SilvanoSorrentino** [comment]
Thank you, that was just a typo in the configuration guide I was following, then.
