### ISSUE TITLE
PDClient: SSL handshake problem

### ISSUE THREAD

**Issue by ssinatti** [phax/peppol-smp-server#96]
Good morning Philip,

I've already red about this problem on other issues, trying to solve by myself following instructions but still have problems.

----

Same problem from IntercentER SMP.

1. ROOT CA (from https://directory.peppol.eu/) imported on my JDK8 cacerts
2. I've tried to disable the hostname verification

Still have the issue :

```
http-bio-8090-exec-7, READ: TLSv1.2 Alert, length = 26
Padded plaintext after DECRYPTION: len = 2
0000: 02 28 .(
http-bio-8090-exec-7, RECV TLSv1.2 ALERT: fatal, handshake_failure
%% Invalidated: [Session-7, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
%% Invalidated: [Session-8, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
http-bio-8090-exec-7, called closeSocket()
http-bio-8090-exec-7, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
http-bio-8090-exec-7, called close()
http-bio-8090-exec-7, called closeInternal(true)
[2019-03-25T10:22:34,778] [SMP-SERVER] [ERROR] [http-bio-8090-exec-7] Internal error in addServiceGroupToIndex for iso6523-actorid-upis::9906:it12312312312 -- com.helger.pd.client.PDClient.lambda$_createDefaultExCb$5f881514$1(PDClient.java:65)
```

I suspect that our problem is that the keystore used for the peppol id registration (it works correctly) is not PKIv3 aligned so the PD does not work.

Thank you in advance.

Stefano

**Comment by phax** [comment]
Hi Stefano,
the Directory just recently moved to a new infrastructure including a new TLS certificate setup.
The current certificate history looks like this:
![grafik](https://user-images.githubusercontent.com/196219/54928930-064b0c80-4f15-11e9-8b9f-3ab1d94253cd.png)
We already had reports, that the intermediate certificate was not part of the chain and that causes issues. So I suggest you add both the DST root as well as the Lets Encrypt intermediate to your trust store and try again. The trust store configured in `pd-client.properties` is also the one used for outgoing HTTPS connections.

**Comment by phax** [comment]
See https://github.com/phax/peppol-commons/blob/master/peppol-commons/src/main/resources/truststore/complete-truststore.jks for an updated trust store that contains the new certificates. It will be part of the 6.2.4 release.

**Comment by ssinatti** [comment]
Hi Philip,
> Hi Stefano,
> the Directory just recently moved to a new infrastructure including a new TLS certificate setup.
> The current certificate history looks like this:
> ![grafik](https://user-images.githubusercontent.com/196219/54928930-064b0c80-4f15-11e9-8b9f-3ab1d94253cd.png)
> We already had reports, that the intermediate certificate was not part of the chain and that causes issues. So I suggest you add both the DST root as well as the Lets Encrypt intermediate to your trust store and try again. 

Done, I've imported on my JVM truststore DTS and LetsEncrypt X3 Authority but I still have the issue : 

`2019-03-26 14:41:23,924 | ERROR | Internal error in addServiceGroupToIndex for iso6523-actorid-upis::9907:12312312311 | com.helger.pd
.client.PDClient | http-nio-9476-exec-4
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
`
That's what I see on my java-cacerts : 

`letsencrypt-x3, 26-mar-2019, trustedCertEntry, 
Impronta digitale certificato (SHA1): E6:A3:B4:5B:06:2D:50:9B:33:82:28:2D:19:6E:FE:97:D5:95:6C:CB
dsrootca-x3, 26-mar-2019, trustedCertEntry, 
Impronta digitale certificato (SHA1): DA:C9:02:4F:54:D8:F6:DF:94:93:5F:B1:73:26:38:CA:6A:D7:7C:13`

>The trust store configured in `pd-client.properties` is also the one used for outgoing HTTPS connections.

I have also tried to import both on jks indicated by pd-client.properties but nothing change on final result, same error.

**Comment by phax** [comment]
Are you using a JKS or a PKCS12 keystore?
Please check if the casing of your key in the configuration file matches the one in the keystore. It's quite a common error, but case sensitivity is important.

**Comment by ssinatti** [comment]
> Are you using a JKS or a PKCS12 keystore?

JKS (it is the standard cacerts keystore of my JVM 8)

> Please check if the casing of your key in the configuration file matches the one in the keystore. It's quite a common error, but case sensitivity is important.

Nothing is changed on my configuration file (are you talink about pd-client.properties, right?)

**Comment by ssinatti** [comment]
Trying with a simple SSL client https://gist.github.com/4ndrej/4547029 (input host:port, e.g.directory.peppol.eu:443) the connections works after having imported DST and Let's, so I don't undertsand what is wrong on PDClient, moreover, I have noticed that both CA was already trusted on my cacerts jks of my jvm

**Comment by ssinatti** [comment]
Really I don't understand where is the problem, following this https://stackoverflow.com/questions/6353849/received-fatal-alert-handshake-failure-through-sslhandshakeexception/6353956#6353956 I have checked possible causes, among jvm params used by my Tomcat 9 I have the explict truststore (-Djavax.net.ssl.trustStore) which includes both CA's certificates (imported new ones).

JVM options : 

`-Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true -Dfile.encoding=UTF-8  -Duser.timezone=Europe/Rome -XX:MaxMetaspaceSize=512m -XX:+DisableExplicitGC -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Djavax.net.ssl.trustStore=/etc/pki/java/cacerts -XX:+DoEscapeAnalysis -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:+ExplicitGCInvokesConcurrent -XX:CMSInitiatingOccupancyFraction=80 -XX:CMSIncrementalSafetyFactor=20 -XX:+UseCMSInitiatingOccupancyOnly -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=3M -XX:-TraceClassUnloading`

**Comment by phax** [comment]
Hi Stefano,
you also need the "directory.peppol.eu" certificate (it is currently (incorrectly) targeted for *.peppol.eu) in the truststore. Is it contained?

**Comment by ssinatti** [comment]
> Hi Stefano,
> you also need the "directory.peppol.eu" certificate (it is currently (incorrectly) targeted for *.peppol.eu) in the truststore. Is it contained?

Yes It is: 

`*.peppol.eu, 26-mar-2019, trustedCertEntry, 
Impronta digitale certificato (SHA1): 72:64:01:B9:B1:4D:3A:5D:4D:54:C2:E6:4E:FA:01:24:F7:BB:7B:F9
`

**Comment by phax** [comment]
Okay thanks. Do you have a timestamp (with timezome) when you tried last - I will ask operations to look in the logs, if they see something

**Comment by ssinatti** [comment]
The last one:

2019-03-26 17:38:01,290 | INFO  | Before HTTP call: PUT **https://test-directory.peppol.eu/indexer/1.0/** (with special HTTP context) | com.helger.httpclient.HttpDebugger | https-jsse-nio-9476-exec-5


**2019-03-26 17:38:01,625** | ERROR | Internal error in addServiceGroupToIndex for iso6523-actorid-upis::9921:sstest001 | com.helger.pd.client.PDClient | https-jsse-nio-9476-exec-5
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Comment by ssinatti** [comment]
Attached 
[ssloutput.txt](https://github.com/phax/peppol-smp-server/files/3009382/ssloutput.txt) 

Output of : openssl s_client -host test-directory.peppol.eu -port 443+

Question : what is that certificate?

**Comment by phax** [comment]
HI Stefano,
thanks - that looks very weird - I was expecting a different one.
I forwarded it to the tech guy but got no response so far.
Will keep you posted.
// Philip

**Comment by ssinatti** [comment]
Good morning,

Let me know, I will looking forward to your feedback.

Stefano

**Comment by aksamit** [comment]
Hi Stefano,

seems as the SSL termination for both test-directory.peppol.eu and directory.peppol.eu was NOT configured to send the Intermediate CA.

This configuration has now been changed and the Intermediate CA is now provided by the server.

Please check if this resolves your problem.

Best regards,

Mikael Aksamit

**Comment by phax** [comment]
@aksamit  Thanks for the swift response. Can you explain why the certificate listed in [ssloutput.txt](https://github.com/phax/peppol-smp-server/files/3009387/ssloutput.txt) is 
```
 0 s:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-10-190-117.eu-west-1.compute.internal/emailAddress=root@ip-10-10-190-117.eu-west-1.compute.internal
   i:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-10-190-117.eu-west-1.compute.internal/emailAddress=root@ip-10-10-190-117.eu-west-1.compute.internal
```

**Comment by ssinatti** [comment]
> Hi Stefano,
> 
> seems as the SSL termination for both test-directory.peppol.eu and directory.peppol.eu was NOT configured to send the Intermediate CA.
> 
> This configuration has now been changed and the Intermediate CA is now provided by the server.
> 
> Please check if this resolves your problem.
> 
> Best regards,
> 
> Mikael Aksamit

Unfortunately nothing is changed calling both **test-directory.peppol.eu**  and  **directory.peppol.eu**.

```
smpserver.restapi.BusinessCardServerAPI | https-jsse-nio-9476-exec-10
2019-03-27 10:51:30,356 | INFO  | Before HTTP call: PUT https://test-directory.peppol.eu/indexer/1.0/ (with special HTTP context) | com.helger.httpclient.HttpDebugger | https-jsse-nio-9476-exec-10
2019-03-27 10:51:30,628 | ERROR | Internal error in addServiceGroupToIndex for iso6523-actorid-upis::9921:sstest001 | com.helger.pd.client.PDClient | https-jsse-nio-9476-exec-10
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

**Comment by aksamit** [comment]
Hi Stefano,

this is the error that is recorded on the server;

```bash
[Wed Mar 27 09:51:30.603235 2019] [ssl:error] [pid 9555] [client 193.xxx.xxx.xxx:43638] AH02261: Re-negotiation handshake failed
[Wed Mar 27 09:51:30.603297 2019] [ssl:error] [pid 9555] SSL Library Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate -- No CAs known to server for verification?
```

Might the case here be that you are not including the client certificate in your request?

Best regards,

Mikael Aksamit

**Comment by ssinatti** [comment]
> Hi Stefano,
> 
> this is the error that is recorded on the server;
> 
> ```shell
> [Wed Mar 27 09:51:30.603235 2019] [ssl:error] [pid 9555] [client 193.xxx.xxx.xxx:43638] AH02261: Re-negotiation handshake failed
> [Wed Mar 27 09:51:30.603297 2019] [ssl:error] [pid 9555] SSL Library Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate -- No CAs known to server for verification?
> ```
> 
> Might the case here be that you are not including the client certificate in your request?

The PDClient is running on Tomcat 9 which is using the JKS provided by Java (standard cacerts) where CA ROOT (DST) and intermediate (Let's encrypt) are both incldued.
In addition, I have my local JKS that is pointend out the client (pd-client.properties) with SMP certificate (this part as installation guide).

In conclusion, how can I include the certificate on PDClient? I thought was enough trusted CAs inside Cacerts's Java or something else is required? 

Regards,
 Stefano
> 
> Best regards,
> 
> Mikael Aksamit

**Comment by aksamit** [comment]
> @aksamit Thanks for the swift response. Can you explain why the certificate listed in [ssloutput.txt](https://github.com/phax/peppol-smp-server/files/3009387/ssloutput.txt) is
> 
> ```
>  0 s:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-10-190-117.eu-west-1.compute.internal/emailAddress=root@ip-10-10-190-117.eu-west-1.compute.internal
>    i:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-10-190-117.eu-west-1.compute.internal/emailAddress=root@ip-10-10-190-117.eu-west-1.compute.internal
> ```

In the setup, the server is sharing multiple SSL hosts on a single IP. So in order for the SSL termination to understand for which host it should return the SSL certificate the hostname must be specified, this can be achieved in the following way;

```
openssl s_client -host test-directory.peppol.eu -servername test-directory.peppol.eu -port 443
```

If the hostname is not specified the SSL termination doesn't understand which mapping it should use and it defaults to the servers self-signed certificate (which you have experienced). I guess this could most likely be configured so that even in the default case it should return a specific certificate.

I do not believe this is related to the experienced handshake failure.

To fully understand the problem here I would suggest @ssinatti to enable full SSL debugging and verify whether the client certificate is actually exchanged during the negotiation. The following JVM options should be enabled in such case;
```
-Djavax.net.debug=all
```

**Comment by ssinatti** [comment]
> > @aksamit Thanks for the swift response. Can you explain why the certificate listed in [ssloutput.txt](https://github.com/phax/peppol-smp-server/files/3009387/ssloutput.txt) is
> > ```
> >  0 s:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-10-190-117.eu-west-1.compute.internal/emailAddress=root@ip-10-10-190-117.eu-west-1.compute.internal
> >    i:/C=--/ST=SomeState/L=SomeCity/O=SomeOrganization/OU=SomeOrganizationalUnit/CN=ip-10-10-190-117.eu-west-1.compute.internal/emailAddress=root@ip-10-10-190-117.eu-west-1.compute.internal
> > ```
> 
> In the setup, the server is sharing multiple SSL hosts on a single IP. So in order for the SSL termination to understand for which host it should return the SSL certificate the hostname must be specified, this can be achieved in the following way;
> 
> ```
> openssl s_client -host test-directory.peppol.eu -servername test-directory.peppol.eu -port 443
> ```
> 
> If the hostname is not specified the SSL termination doesn't understand which mapping it should use and it defaults to the servers self-signed certificate (which you have experienced). I guess this could most likely be configured so that even in the default case it should return a specific certificate.
> 
> I do not believe this is related to the experienced handshake failure.
> 
> To fully understand the problem here I would suggest @ssinatti to enable full SSL debugging and verify whether the client certificate is actually exchanged during the negotiation. The following JVM options should be enabled in such case;
> 
> ```
> -Djavax.net.debug=all
Ok and thank you for your suggestion, the problem is : what should I check/verify? because server log is very "huge" and difficult for reading with that option.

Stefano
> ```
> 
> Best regards,
> 
> Mikael Aksamit

**Comment by phax** [comment]
Hi Stefano,
just send it to me zipped by email.
What exact Tomcat version are you using?
What Java version are you using?
Mike wont follow up from here.
// Philip

**Comment by ssinatti** [comment]
> Hi Stefano,
> just send it to me zipped by email.
Attached a tar.gz file
> What exact Tomcat version are you using?
Tomcat 9 but i've tried also with an old installation with Tomcat 7, same issue
> What Java version are you using?
jdk1.8.0_45 (test) openjdk1.8.0_191 (prod), same issue
> Mike wont follow up from here.
> // Philip

Stefano
[catalina.out.tar.gz](https://github.com/phax/peppol-smp-server/files/3013755/catalina.out.tar.gz)

**Comment by phax** [comment]
According to line 216962 you are using old certificates. It's the old directory.peppol.eu certificates.
And you have configured an old v2 SMP certificate.
Please update to a v3 SMP certificate!

**Comment by phax** [comment]
Were you able to solve the issue @ssinatti ?

**Comment by ssinatti** [comment]
Not yet, at the moment you can closed or suspend the issue, I will post as soon as possible the resolution, ok? 
Thank you very much.

Regards,
 Stefano

**Comment by phax** [comment]
Thanks Stefano - I will leave it open and check later. Just keep me posted - I won't work on it atm

**Comment by phax** [comment]
@ssinatti Did you manage to get it working?

**Comment by phax** [comment]
You can reopen it, once you have news on this issue.

**Comment by ssinatti** [comment]
Hello @phax,

In Italy we say : "better late than never"; finally we managed the "PKIv3 problem" related to the BC registration/de-registration.

Thank you very much for your help and, as usual, for your patience.

Regards,
 Stefano

**Comment by phax** [comment]
@ssinatti Thanks for the heads up :D Congrats you made it.
