### ISSUE TITLE
Difficulties setting up the keystore

### ISSUE THREAD

**Issue by daniel-filipe-lobo** [phax/peppol-smp-server#98]
Hi,

We are part of a CEF consortium to have interoperability for the eProcurement pre-award, and we are trying to setup the four corner model with Bescha from Germany.
For this purpose, and only for the development environment, we were wanting to setup our own SMP with Bescha so we don’t have to wait for PEPPOL or Bescha federal services.
The setup has been straight forward but we are not being able to configure the key store. It says it does not detect it.

Can you help us?

**Comment by phax** [comment]
Hi,
well you need a PEPPOL test certificate for correct initialization.
In the meantime - to get it "somehow" working - you can also use a self signed certificate, but that results in only partial PEPPOL compliance, as e.g. the SML registration and the Directory integration will not work.
So just create a self signed certificate, configure the JKS or PKCS12 keystore in the "smp-server.properties" file and restart the SMP or click the "reload" button in the "Certificate details" page.
hth

**Comment by phax** [comment]
@daniel-filipe-lobo Did my answer help you? Is there anything else you need to know?

**Comment by phax** [comment]
You can re-open the issue again if you have input
